export { default as Header } from './Header';
export { default as HeroSection } from './HeroSection';
export { default as SectionOne } from './SectionOne';
export { default as SectionTwo } from './SectionTwo';
export { default as Portfolio } from './Portfolio';
export { default as SectionThree } from './SectionThree';
export { default as SectionFour } from './SectionFour';
export { default as OurCustomerSay } from './OurCustomerSay';
export { default as OurClients } from './OurClients';
export { default as Blog } from './Blog';
export { default as Footer } from './Footer';
export { default as FooterTop } from './FooterTop';
export { default as HeroSectionLanding } from './HeroSectionLanding';
export { default as LandingSectionOne } from './LandingSectionOne';
export { default as LandingSectionTwo } from './LandingSectionTwo';
export { default as OneClickSection } from './OneClickSection';
export { default as PortfolioTabSection } from './PortfolioTabSection';
export { default as LandingSectionIntegration } from './LandingSectionIntegration';
export { default as Faq } from './Faq';
export { default as MobileAppScroll } from './MobileAppScroll';
export { default as PageLayout } from './PageLayout';
export { default as ContentListSection } from './ContentListSection';
export { default as Diagram } from './Diagram';
export { default as RequestDemoModal } from './RequestDemoModal';
export { default as IndustrySection } from './IndustrySection';
export { default as ContentListSectionTwo } from './ContentListSectionTwo';
export { default as HeroSubpage } from './HeroSubpage';
export { default as ContentListSectionThree } from './ContentListSectionThree';

export * from "./Card";
export * from "./Utils";